version: '3'

services:
  authority0:
    image: parity/parity:${PARITY_VERSION}
    command:
      --config /parity/config/authority.toml
      --engine-signer 0x00bd138abd70e2f00903268f3db08f2d25677c9e
    volumes:
      - ./parity/config:/parity/config:ro
      - authorities0:/root/.local/share/io.parity.ethereum/
      - ./parity/authorities/authority0.json:/root/.local/share/io.parity.ethereum/keys/${NETWORK_NAME}/authority.json:ro
      - ./parity/authorities/authority0.pwd:/parity/authority.pwd:ro
      - ./parity/authorities/authority0.key:/root/.local/share/io.parity.ethereum/network/key:ro
    networks:
      app_net:
        ipv4_address: 172.16.0.10
    restart: always

  authority1:
    image: parity/parity:${PARITY_VERSION}
    command:
      --config /parity/config/authority.toml
      --engine-signer 0x00aa39d30f0d20ff03a22ccfc30b7efbfca597c2
    volumes:
      - ./parity/config:/parity/config:ro
      - authorities1:/root/.local/share/io.parity.ethereum/
      - ./parity/authorities/authority1.json:/root/.local/share/io.parity.ethereum/keys/${NETWORK_NAME}/authority.json:ro
      - ./parity/authorities/authority1.pwd:/parity/authority.pwd:ro
      - ./parity/authorities/authority1.key:/root/.local/share/io.parity.ethereum/network/key:ro
    networks:
      app_net:
        ipv4_address: 172.16.0.11
    restart: always

  authority2:
    image: parity/parity:${PARITY_VERSION}
    command:
      --config /parity/config/authority.toml
      --engine-signer 0x002e28950558fbede1a9675cb113f0bd20912019
    volumes:
      - ./parity/config:/parity/config:ro
      - authorities2:/root/.local/share/io.parity.ethereum/
      - ./parity/authorities/authority2.json:/root/.local/share/io.parity.ethereum/keys/${NETWORK_NAME}/authority.json:ro
      - ./parity/authorities/authority2.pwd:/parity/authority.pwd:ro
      - ./parity/authorities/authority2.key:/root/.local/share/io.parity.ethereum/network/key:ro
    networks:
      app_net:
        ipv4_address: 172.16.0.12
    restart: always

  public-node:
    image: parity/parity:${PARITY_VERSION}
    command: --config /parity/config/member.toml
    volumes:
      - ./parity/config:/parity/config:ro
    ports:
      - 8545:8545
      - 8546:8546
    networks:
      app_net:
        ipv4_address: 172.16.0.20
    restart: always

  monitor:
    image: buythewhale/ethstats_monitor
    volumes:
      - ./monitor/app.json:/home/ethnetintel/eth-net-intelligence-api/app.json:ro
    networks:
      app_net:
        ipv4_address: 172.16.0.100
    restart: always

  dashboard:
    build: dashboard
    volumes:
      - ./dashboard/ws_secret.json:/eth-netstats/ws_secret.json:ro
    ports:
      - 3001:3000
    networks:
      app_net:
        ipv4_address: 172.16.0.200
    restart: always

  explorer:
    build: explorer
    volumes:
      - ./explorer/config.json:/explorer/app/config.json:ro
    ports:
      - 3002:8000
    networks:
      app_net:
        ipv4_address: 172.16.0.201
    restart: always

volumes:
  authorities0:
  authorities1:
  authorities2:

networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.16.0.1/24
