[parity]
chain = "/parity/config/chain.json"
auto_update = "all"

[network]
bootnodes = [
  "enode://147573f46fe9f5cc38fbe070089a31390baec5dd2827c8f2ef168833e4d0254fbee3969a02c5b9910ea5d5b23d86a6ed5eabcda17cc12007b7d9178b6c697aa5@172.16.0.10:30303"
]

[footprint]
fat_db = "on"

[rpc]
port = 8545
interface = "0.0.0.0"
processing_threads = 10
cors = ["all"]
hosts = ["all"]
apis = ["safe"]

[websockets]
port = 8546
interface = "local"
max_connections = 1000
origins = ["all"]
hosts = ["all"]
apis = ["safe"]

[ipc]
disable = true

[secretstore]
disable = true

[ui]
disable = true
